kind: containerapp
location: eastus
name: go-service
resourceGroup: <<grupo-recursos>>
type: Microsoft.App/containerApps
tags:
properties:
  managedEnvironmentId: /subscriptions/<<subscription-key>>/resourceGroups/<<grupo-recursos>>/providers/Microsoft.App/managedEnvironments/<<aca-environment-name>>
  configuration:
    activeRevisionsMode: Single
    secrets:
      - name: myregistrypassword
        value: "registry-secret-here"
    registries:
      - passwordSecretRef: myregistrypassword
        server: <<registry>>.azurecr.io
        username: <<registry-user>>
    dapr:
      appId: go-app
      appPort: 8050
      appProtocol: http
      enabled: true
  template:
    revisionSuffix: 202205011526
    containers:
      - image: <<registry>>.azurecr.io/go-service:20220501124932219820
        name: go-service
        env:
          - name: HTTP_PORT
            value: 8050
        resources:
          cpu: 1
          memory: 2Gi
    scale:
      minReplicas: 1
      maxReplicas: 3